### ISSUE TITLE
Error building on Arch Linux

### ISSUE THREAD

**Issue by flysand7** [vmt/udis86#146]
I'm encountering building errors

```
$ ./autogen.sh
$ ./configure
$ make
```

The make produces the following output:

```
make  all-recursive
make[1]: Entering directory '/home/bumbread/udis86'
Making all in scripts
make[2]: Entering directory '/home/bumbread/udis86/scripts'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/bumbread/udis86/scripts'
Making all in libudis86
make[2]: Entering directory '/home/bumbread/udis86/libudis86'
/sbin/python ../scripts/ud_itab.py ../docs/x86/optable.xml .
Traceback (most recent call last):
  File "/home/bumbread/udis86/libudis86/../scripts/ud_itab.py", line 379, in <module>
    main()
  File "/home/bumbread/udis86/libudis86/../scripts/ud_itab.py", line 374, in main
    tables = UdOpcodeTables(xml=sys.argv[1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bumbread/udis86/scripts/ud_opcode.py", line 330, in __init__
    self.printStats()
  File "/home/bumbread/udis86/scripts/ud_opcode.py", line 575, in printStats
    self.pprint()
  File "/home/bumbread/udis86/scripts/ud_opcode.py", line 557, in pprint
    printWalk(self.root)
  File "/home/bumbread/udis86/scripts/ud_opcode.py", line 554, in printWalk
    printWalk(e, indent + "    |")
  File "/home/bumbread/udis86/scripts/ud_opcode.py", line 554, in printWalk
    printWalk(e, indent + "    |")
  File "/home/bumbread/udis86/scripts/ud_opcode.py", line 556, in printWalk
    self.log("%s    |-<%02x> %s" % (indent, k, e))
             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: %x format: an integer is required, not float
make[2]: *** [Makefile:748: itab.c] Error 1
make[2]: Leaving directory '/home/bumbread/udis86/libudis86'
make[1]: *** [Makefile:483: all-recursive] Error 1
make[1]: Leaving directory '/home/bumbread/udis86'
make: *** [Makefile:394: all] Error 2
```

**Comment by domhnallc** [comment]
Same error on Ubuntu24.04.2:

    self.log("%s    |-<%02x> %s" % (indent, k, e))
             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: %x format: an integer is required, not float
make[2]: *** [Makefile:748: itab.h] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:748: itab.c] Error 1
make[2]: Leaving directory '/home/domhnall/udis86/libudis86'
make[1]: *** [Makefile:483: all-recursive] Error 1
make[1]: Leaving directory '/home/domhnall/udis86'
make: *** [Makefile:394: all] Error 2
